apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nodejs

resources:
  - deployment.yaml
  - service.yaml
  # - ingress.yaml

configMapGenerator:
  - files:
      - configmaps/default.conf
    name: default-conf
  - files:
      - configmaps/nginx.conf
    name: nginx-conf
  - files:
      - configmaps/dd-config.json.in
    name: dd-config
