apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"80":"nginx-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nginx-backendconfig
spec:
  securityPolicy:
    name: "security-policy"
  timeoutSec: 30
  logging:
    enable: true
    sampleRate: 1.0
  cdn:
    enabled: false
  connectionDraining:
    drainingTimeoutSec: 0
  healthCheck:
    type: HTTP
    requestPath: /nginx_status
    port: 8080
  sessionAffinity: 
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 300
---